apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falcon-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: workspace-falcon-7b-instruct
            port:
              number: 80
